name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install and build SignalR.HubApi.Ui
        run: |
          cd src/SignalR.HubApi.Ui
          npm ci
          npm run build
      - name: Test SignalR.HubApi.Ui
        run: | 
          cd src/SignalR.HubApi.Ui
          npm run test
      - name: Copy SignalR.HubApi.Ui distribution to SignalR.HubApi/web
        run: mv -v src/SignalR.HubApi.Ui/dist src/SignalR.HubApi/web
      - name: Build SignalR.HubApi solution
        run: dotnet build src/SignalR.HubApi.sln --configuration Release
      - name: Test SignalR.HubApi solution
        run: dotnet test src/SignalR.HubApi.sln --verbosity normal
